site_name: My Docs
plugins:
  - search
theme:
  name: material
  features:
    - content.code.annotate
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: '*'
          class: '*'
          format: !!python/name:superfences_examples.prefix.formatter
          validator: !!python/name:superfences_examples.prefix.validator
