site_name: My Docs
plugins:
  - search
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: prefix
          class: prefix
          format: !!python/name:superfences_examples.prefix.prefix_format
          validator: !!python/name:superfences_examples.prefix.prefix_validator
        - name: venv
          class: venv
          format: !!python/name:superfences_examples.venv.venv_format
          validator: !!python/name:superfences_examples.venv.venv_validator
